FROM --platform=linux/amd64 node:18.14.2 AS base

RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

RUN npm install -g pnpm

WORKDIR /app

# Copy package.json and pnpm-lock.yaml if you have it
COPY package.json package.json

# Install dependencies
RUN pnpm install


# Copy the rest of the application
COPY . .

# ===== Development Stage =====
FROM base AS dev

EXPOSE 3000 

CMD [ "pnpm", "run", "start:dev" ]
# ===== Development Stage =====

# ===== Production Stage =====
FROM base AS prod

WORKDIR /app/apps/dashboard

# Expose the port the app runs on
EXPOSE 3000

# Build the NestJS app
RUN pnpm build

CMD ["node", ".output/server/index.mjs"]
# ===== Production Stage =====
